name: Node.js Package

on:
  push:
    branches: [main, next, beta, alpha]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - run: npm run semantic-release
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      GH_TOKEN: ${{secrets.GH_TOKEN}}
